# Generated by Django 4.2.2 on 2023-06-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='calLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DailyCalorieLimit', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
