# Generated by Django 4.2.2 on 2023-06-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0002_callimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
