# Generated by Django 4.2.2 on 2023-06-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieapp', '0003_alter_food_calories_alter_food_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.IntegerField(null=True),
        ),
    ]
